---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: value
  template:
    metadata:
      labels:
        app: value
    spec:
      containers:
        - name: container-name
          image: nginx
          imagePullPolicy: Always
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: secret-value
                  key: kafka-brokers
            - name: ***
              value: ***
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app:  value
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
